config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :users
  end

  namespace :users do
    resources :loanables
    get "loaned", to: "loanables#loaned", as: "loaned"
  end

  resources :loanables, only: [:index, :show] do
    resources :loan_contracts, only: [:create], module: :loanables
  end

  resources :bulk_purchases, only: [:index]

  get "/signup",  to: "users/registrations#new", as: "signup"
  post "/signup", to: "users/registrations#create"
  get "/karma",   to: "users/registrations#karma"

  get "/signin",      to: "users/sessions#new", as: "signin"
  post "/signin",     to: "users/sessions#create"
  delete "/signout",  to: "users/sessions#destroy", as: "signout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan_contract.rb
class LoanContract < ApplicationRecord
  belongs_to :loanable
  has_one :borrower
end

app/models/loanable.rb
class Loanable < ApplicationRecord
  belongs_to :user
  has_many :loan_contracts
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, length: { minimum: 8 }, allow_nil: true

  has_many :loanables
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:admin, @user], notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user ||= nil
    end
  end

  def authenticate_user
    if current_user
    else
      flash[:alert] = "you need to be signed in"
      redirect_to root_url
    end
  end
end

app/controllers/bulk_purchases_controller.rb
class BulkPurchasesController < ApplicationController
  layout 'bulk_purchases'

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to loanables_path
    else
      render :index, locals: {}
    end
  end
end

app/controllers/loanables/loan_contracts_controller.rb
class Loanables::LoanContractsController < ApplicationController
  before_action :authenticate_user

  def create
    @loan_contract = LoanContract.new(
      loan_contract_params.merge({
        loanable_id: params[:loanable_id],
        borrower_id: current_user.id
      })
    )

    if @loan_contract.save
      redirect_to loanables_path
    else
      flash[:alert] = "something is wrong, try again"
      redirect_to loanable_path(Loanable.find(params[:loanable_id]))
    end
  end

  private

    def loan_contract_params
      params.require(:loan_contract).permit(:start, :end)
    end
end

app/controllers/loanables_controller.rb
class LoanablesController < ApplicationController
  before_action :authenticate_user
  before_action :set_loanable, only: [:show]

  def index
    @loanables = Loanable
      .includes(:loan_contracts)
      .where("loanables.end >= ?", Time.zone.now)
      .where.not("loanables.user_id": current_user.id)
      .reject { |loanable| loanable.loan_contracts.count > 0 }
  end

  def show
    @loan_contract = @loanable.loan_contracts.new(start: Time.zone.now, end: @loanable.end)
  end

  private
    def set_loanable
      @loanable = Loanable.find(params[:id])
    end
end

app/controllers/users/loanables_controller.rb
class Users::LoanablesController < ApplicationController
  before_action :authenticate_user
  before_action :set_loanable, only: [:show, :edit, :update, :destroy]

  # GET /loanables
  # GET /loanables.json
  def index
    @loanables = current_user.loanables.includes(:loan_contracts).all
  end

  # GET /loanables/1
  # GET /loanables/1.json
  def show
  end

  # GET /loanables/new
  def new
    @loanable = current_user.loanables.new
  end

  # GET /loanables/1/edit
  def edit
  end

  # POST /loanables
  # POST /loanables.json
  def create
    @loanable = current_user.loanables.new(loanable_params)

    respond_to do |format|
      if @loanable.save
        format.html { redirect_to users_loanable_path(@loanable), notice: 'Loanable was successfully created.' }
        format.json { render :show, status: :created, location: @loanable }
      else
        format.html { render :new }
        format.json { render json: @loanable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loanables/1
  # PATCH/PUT /loanables/1.json
  def update
    respond_to do |format|
      if @loanable.update(loanable_params)
        format.html { redirect_to [:users, @loanable], notice: 'Loanable was successfully updated.' }
        format.json { render :show, status: :ok, location: @loanable }
      else
        format.html { render :edit }
        format.json { render json: @loanable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loanables/1
  # DELETE /loanables/1.json
  def destroy
    @loanable.destroy
    respond_to do |format|
      format.html { redirect_to users_loanables_url, notice: 'Loanable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def loaned
    @loanables = Loanable.joins(:loan_contracts).where("loan_contracts.borrower_id = ?", current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loanable
      @loanable = current_user.loanables.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loanable_params
      params.require(:loanable).permit(:title, :description, :location, :contact, :end, :state, :url)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(signup_params)

    if @user.save
      flash[:notice] = t("user.registration.confirm_email")
      redirect_to root_path
    else
      render :new
    end
  end

  def karma
  end

  private

    def signup_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_name(signin_params[:name])
    if @user && @user.authenticate(signin_params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Rentero!"
      redirect_to root_url
    else
      @user = User.new
      flash[:alert] = "Invalid name or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully signed out!"
    redirect_to root_url
  end

  private

    def signin_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loanables_helper.rb
module LoanablesHelper
end

app/helpers/users/session_helper.rb
module Users::SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.slim
= form_for [:admin, @user] do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label :password
    = f.password_field :password
  .actions = f.submit

app/views/admin/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', admin_users_path

app/views/admin/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Password
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.password
        td = link_to 'Show', [:admin, user]
        td = link_to 'Edit', edit_admin_user_path(user)
        td = link_to 'Destroy', [:admin, user], data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', admin_users_path

app/views/admin/users/show.html.slim
p
  strong Name:
  = @user.name
p
  strong Password:
  = @user.password

=> link_to 'Edit', edit_admin_user_path(@user)
'|
=< link_to 'Back', admin_users_path

app/views/bulk_purchases/index.html.slim
.d-flex.justify-content-around.flex-wrap
  .w-25.m-1
    = image_tag "bulk_1.jpg", class: "img-thumbnail"
  .w-25.m-1
    = image_tag "bulk_2.jpg", class: "img-thumbnail"
  .w-25.m-1
    = image_tag "bulk_3.jpg", class: "img-thumbnail"

app/views/home/index.html.slim
h1 Home

p Welcome to Rentero.

app/views/layouts/application.html.slim
doctype html
html
  head
    title Rentero
    = csrf_meta_tags
    = csp_meta_tag

    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag  "application"
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    header
      nav.navbar.navbar-expand-lg.navbar-light.bg-light
        a.navbar-brand href=root_path
          = t("application.name")
        button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
          span.navbar-toggler-icon

        div.collapse.navbar-collapse#navbarSupportedContent
          - if current_user
            ul.navbar-nav.mr-auto
              li.nav-item
                = link_to "My Loanables", users_loanables_path, class: "nav-link"
              li.nav-item
                = link_to "Bulk Purchases", bulk_purchases_path, class: "nav-link"
              li.nav-item
                = link_to "Loaned", users_loaned_path, class: "nav-link"
            ul.navbar-nav
              li.nav-item.dropdown
                a.nav-link.dropdown-toggle#navbarDropdown href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                  = current_user.name.humanize
                div.dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdown"
                  = link_to "Karma", karma_path, class: "dropdown-item"
                  <div class="dropdown-divider"></div>
                  = link_to "Sign Out", signout_path, method: :delete, class: "dropdown-item"
          - else
            ul.navbar-nav.mr-auto
            ul.navbar-nav
              li.nav-item
                = link_to "Sign Up", signup_path, class: "nav-link"
              li.nav-item
                = link_to "Sign In", signin_path, class: "nav-link"

    .container
      <br>
      - flash.each do |name, msg|
        - if name == "alert"
          = content_tag :div, msg, class: "alert alert-danger"
        - else
          = content_tag :div, msg, class: "alert alert-info"

      = yield

app/views/layouts/bulk_purchases.html.slim
doctype html
html
  head
    title Rentero
    = csrf_meta_tags
    = csp_meta_tag

    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag  "application"
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    header
      nav.navbar.navbar-expand-lg.navbar-light.bg-light
        a.navbar-brand href=root_path
          = t("application.name")
        button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
          span.navbar-toggler-icon

        div.collapse.navbar-collapse#navbarSupportedContent
          - if current_user
            ul.navbar-nav.mr-auto
              li.nav-item
                = link_to "My Loanables", users_loanables_path, class: "nav-link"
              li.nav-item
                = link_to "Bulk Purchases", bulk_purchases_path, class: "nav-link"
              li.nav-item
                = link_to "Loaned", users_loaned_path, class: "nav-link"
            ul.navbar-nav
              li.nav-item.dropdown
                a.nav-link.dropdown-toggle#navbarDropdown href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                  = current_user.name.humanize
                div.dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdown"
                  = link_to "Karma", karma_path, class: "dropdown-item"
                  <div class="dropdown-divider"></div>
                  = link_to "Sign Out", signout_path, method: :delete, class: "dropdown-item"
          - else
            ul.navbar-nav.mr-auto
            ul.navbar-nav
              li.nav-item
                = link_to "Sign Up", signup_path, class: "nav-link"
              li.nav-item
                = link_to "Sign In", signin_path, class: "nav-link"

    .container-fluid
      <br>
      - flash.each do |name, msg|
        - if name == "alert"
          = content_tag :div, msg, class: "alert alert-danger"
        - else
          = content_tag :div, msg, class: "alert alert-info"

      = yield

app/views/loanables/index.html.slim
h1 All Loanables

- @loanables.each do |l|
  a.loanable href=loanable_path(l)
    div.card.mb-12
      div.row.no-gutters
        div.col-md-3
          img.card-img src=l.url  alt="..."
        div.col-md-9
          .card-body
            h5.card-title
              = l.title.titleize
            p.card-text
              strong Description:&nbsp;
              = l.description
              br
              strong Location:&nbsp;
              = l.location
              br
              strong Contact:&nbsp;
              = l.contact
              br
              strong End Available Date:&nbsp;
              = local_time(l.end) if l.end

app/views/loanables/show.html.slim
h1 = @loanable.title.titleize

p
  strong Description:&nbsp;
  = @loanable.description
p
  strong Location:&nbsp;
  = @loanable.location
p
  strong Contact:&nbsp;
  = @loanable.contact
p
  strong Owner:&nbsp;
  = @loanable.user.name
p
  strong End Date Time:&nbsp;
  = local_time(@loanable.end) if @loanable.end

img.card-img src=@loanable.url  alt="..." style="max-width:512px;"

<hr>

h2 Loan Form

= bootstrap_form_for(@loan_contract, url: loanable_loan_contracts_path(@loanable)) do |f|
  = f.datetime_field :start, min: Time.zone.now
  = f.datetime_field :end, max: @loanable.end
  = f.primary "loan"

app/views/users/loanables/_form.html.slim
= bootstrap_form_for(@loanable, url: users_loanables_path) do |f|
  = f.text_field :title
  = f.text_area :description
  = f.text_field :location
  = f.text_field :contact
  = f.datetime_field :end
  = f.string :url
  - if @loanable.loan_contracts.count > 0
    = f.text_field :state
  = f.primary

app/views/users/loanables/edit.html.slim
h1 Editing loanable

= bootstrap_form_for(@loanable, url: users_loanable_path) do |f|
  = f.text_field :title
  = f.text_area :description
  = f.text_field :location
  = f.text_field :contact
  = f.datetime_field :end
  = f.text_field :url
  - if @loanable.loan_contracts.count > 0
    = f.text_field :state
  = f.primary


=> link_to 'Show', @loanable, class: "btn btn-light"
'|
=< link_to 'Back', users_loanables_path, class: "btn btn-dark"

app/views/users/loanables/index.html.slim
h1 My Loanables

p = link_to 'New Loanable', new_users_loanable_path, class: "btn btn-primary"

hr

table.table.table-borderless
  tbody
    th
      tr
        th style="width: 80%"
          h2 Available
        th style="width: 20%"
    - @loanables.reject { |l| l.loan_contracts.count > 0 }.each do |l|
      tr
        td
          a.loanable href=users_loanable_path(l)
            .card
              .row.no-gutters
                .col-md-4
                  img.card-img src=l.url alt="..."
                .col-md-8
                  .card-body
                    h5.card-title
                      = l.title.titleize
                    p.card-text
                      strong Description:&nbsp;
                      = l.description
                      br
                      strong Location:&nbsp;
                      = l.location
                      br
                      strong Contact:&nbsp;
                      = l.contact
                      br
                      strong End Available Date:&nbsp;
                      = local_time(l.end) if l.end

        td
          = link_to 'Edit', edit_users_loanable_path(l), class: "btn btn-light"
          <br>
          = link_to 'Destroy', users_loanable_path(l), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-dark"

hr

table.table.table-borderless
  tbody
    th
      tr
        th style="width: 80%"
          h2 On Loan
        th style="width: 20%"
    - @loanables.select { |l| l.loan_contracts.count > 0 }.each do |l|
      tr
        td
          a.loanable href=users_loanable_path(l)
            .card
              .row.no-gutters
                .col-md-4
                  img.card-img src=l.url alt="..."
                .col-md-8
                  .card-body
                    h5.card-title
                      = l.title.titleize
                    p.card-text
                      strong Description:&nbsp;
                      = l.description
                      br
                      strong Location:&nbsp;
                      = l.location
                      br
                      strong Contact:&nbsp;
                      = l.contact
                      br
                      strong End Available Date:&nbsp;
                      = local_time(l.end) if l.end
                      br
                      strong State:&nbsp;
                      = l.state

        td
          = link_to 'Edit', edit_users_loanable_path(l), class: "btn btn-light"
          <br>
          = link_to 'Destroy', users_loanable_path(l), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-dark"

app/views/users/loanables/loaned.html.slim
h1 I loaned

- @loanables.each do |l|
  div.card.mb-12
    div.row.no-gutters
      div.col-md-3
        img.card-img src=l.url  alt="..."
      div.col-md-9
        .card-body
          h5.card-title
            = l.title.titleize
          p.card-text
            strong Description:&nbsp;
            = l.description
            br
            strong Location:&nbsp;
            = l.location
            br
            strong Contact:&nbsp;
            = l.contact
            br
            strong End Available Date:&nbsp;
            = local_time(l.end) if l.end
            br
            strong State:&nbsp;
            = l.state

app/views/users/loanables/new.html.slim
h1 New loanable

= bootstrap_form_for(@loanable, url: users_loanables_path) do |f|
  = f.text_field :title
  = f.text_area :description
  = f.text_field :location
  = f.text_field :contact
  = f.datetime_field :end
  = f.text_field :url
  - if @loanable.loan_contracts.count > 0
    = f.text_field :state
  = f.primary

= link_to 'Back', users_loanables_path, class: "btn btn-dark"

app/views/users/loanables/show.html.slim
h1 = @loanable.title.titleize
p
  strong Description:&nbsp;
  = @loanable.description
p
  strong Location:&nbsp;
  = @loanable.location
p
  strong Contact:&nbsp;
  = @loanable.contact
p
  strong End Date Time:&nbsp;
  = local_time(@loanable.end) if @loanable.end

img.card-img src=@loanable.url alt="..." style="max-width:512px;"

hr

=> link_to 'Edit', edit_users_loanable_path(@loanable), class: "btn btn-light"
'|
=< link_to 'Back', users_loanables_path, class: "btn btn-dark"